version: '3.7'
services:
  jenkins:      
    build: ./
    privileged: true
    ports:
      - "50000:50000"
      - "9000:8080"
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /usr/bin/docker:/usr/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock
  nodejs:
    build: ./microservice-node
    ports:
      - "3001:3001"
    volumes:
      - ./microservice-node:/service
      - /service/node_modules
  webclient:
    build: ./microservice-react
    ports:
      - "8081:80"
    volumes:
      - ./microservice-react:/service
      - /service/node_modules
  nginx: 
    build: ./microservice-nginx
    ports:
      - "80:80"
    depends_on:
      - webclient
      - jenkins
