version: '3'
services:
  nodejs:
    build: ./microservice-node-react/server
    ports:
      - "3001:3001"
    entrypoint: ['node', 'server.js']
    volumes:
      - ./microservice-node-react/server:/service
      - /service/node_modules
  webclient:
    build: ./microservice-node-react/client
    ports:
      - "8081:80"
    entrypoint: ['npm', 'start']
    volumes:
      - ./microservice-node-react/client:/service
      - /service/node_modules
  nginx: 
    build: ./microservice-nginx
    ports:
      - "80:80"
    depends_on:
      - webclient


