version: '3.7'
services:
  jenkins:      
    build: ./
    privileged: true
    user: root
    ports:
      - "50000:50000"
      - "9000:8080"
    container_name: jenkins
    volumes:
      - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
  nodejs:
    build: ./microservice-node-react/server
    ports:
      - "3001:3001"
    volumes:
      - ./microservice-node-react/server:/service
      - /service/node_modules
  webclient:
    build: ./microservice-node-react/client
    ports:
      - "8081:80"
    volumes:
      - ./microservice-node-react/client:/service
      - /service/node_modules
  nginx: 
    build: ./microservice-nginx
    ports:
      - "80:80"
    depends_on:
      - webclient
      - jenkins
